//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public int GenreID { get; set; }
        public string Year { get; set; }
        public Nullable<int> Pages { get; set; }
        public int LanguageID { get; set; }
        public string CoverFileName { get; set; }
        public string Description { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
